### ISSUE TITLE
Doesn't exist /usr/local/Cellar/ruby/2.0.0-p247/bin/ruby20

### ISSUE THREAD

**Issue by supermomonga** [splhack/homebrew-splhack#1]
I installed ruby 2.0.0-p247, but `/usr/local/Cellar/ruby/2.0.0-p247/bin/ruby20` doesn't created, so I got the error while installing macvim-kaoriya.

```
❯ ls /usr/local/Cellar/ruby/2.0.0-p247/bin
erb gem irb rake    rdoc    ri  ruby    testrb
```

https://github.com/splhack/homebrew-splhack/blob/master/macvim-kaoriya.rb#L27

I think maybe this line should be this.
`"#{HOMEBREW_PREFIX}/Cellar/ruby/2.0.0-p247/bin/ruby",`

**Comment by splhack** [comment]
Could you try the latest version?
