### ISSUE TITLE
How can I install macvim-kaoriya? OSX10.10.2

### ISSUE THREAD

**Issue by kobayashi** [splhack/homebrew-splhack#2]
I got following error when I install macvim-kaoriya through brew install on OSX 10.10.2

% brew install --HEAD macvim-kaoriya                                                                                                                                               ==> Installing macvim-kaoriya from splhack/homebrew-splhack
==> Cloning https://github.com/splhack/macvim.git
Updating /Library/Caches/Homebrew/macvim-kaoriya--git
==> Checking out branch master
Error: brew install python3 ruby lua lua52 luajit
can't find /usr/local/Cellar/python3/3.4.0_1/bin/python3
can't find /usr/local/Cellar/ruby/2.1.1_1/bin/ruby
can't find /usr/local/Cellar/lua/5.1.5/bin/lua
can't find /usr/local/Cellar/lua52/5.2.3/bin/lua
can't find /usr/local/Cellar/luajit/2.0.3/bin/luajit

The following packages are installed.
Only lua52 is not installed and not found.
% ls /usr/local/Cellar/python3
3.4.2_1
% ls /usr/local/Cellar/ruby/ 
2.2.0
% ls /usr/local/Cellar/lua/
5.2.3_1
% ls /usr/local/Cellar/lua52/ 
ls: /usr/local/Cellar/lua52/: No such file or directory
% ls /usr/local/Cellar/luajit/
2.0.3_1

**Comment by splhack** [comment]
Could you try the latest version?
